name: wazo-call-recording-uuid
namespace: wazocommunication
version: 1.1.0
author: Wazo authors
display_name: Call Recording UUID Migration
plugin_format_version: 1
min_wazo_version: 24.10
max_wazo_version: 24.11
tags:
  - cdr
  - recording
homepage: https://github.com/wazo-communication/wazo-call-recording-uuid-plugin
